module.exports = {
  A1: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  A2: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  A3: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  A4: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  A5: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  A6: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  B1: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+5",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  B2: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+5",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  B3: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+5",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  B4: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+5",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  C1: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 240,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  C2: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 240,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  C3: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 240,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  C4: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 240,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D11: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D12: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D13: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D14: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D15: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D16: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D21: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: true,
      clickt: false,
      clickt10: false,
    },
  ],
  D22: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: true,
      clickt: false,
      clickt10: false,
    },
  ],
  D23: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: true,
      clickt: false,
      clickt10: false,
    },
  ],
  D24: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: true,
      clickt: false,
      clickt10: false,
    },
  ],
  D25: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: true,
      clickt: false,
      clickt10: false,
    },
  ],
  D26: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: true,
      clickt: false,
      clickt10: false,
    },
  ],
  D31: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: true,
      clickt10: true,
    },
  ],
  D32: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: true,
      clickt10: true,
    },
  ],
  D33: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: true,
      clickt10: true,
    },
  ],
  D34: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: true,
      clickt10: true,
    },
  ],
  D35: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: true,
      clickt10: true,
    },
  ],
  D36: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: true,
      clickt10: true,
    },
  ],
  D41: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D42: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D43: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D44: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D45: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  D46: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  E21: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  E22: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  E23: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  E24: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  E25: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  E26: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
  ],
  
  E11: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      predictLongRunning: true,
    },
  ],
  E12: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      predictLongRunning: true,
    },
  ],
  E13: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      predictLongRunning: true,
    },
  ],
  E14: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      predictLongRunning: true,
    },
  ],
  E15: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      predictLongRunning: true,
    },
  ],
  E16: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "10",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      predictLongRunning: true,
    },
  ],
  E31: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      fadeDistant: false,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      processInfo:
        "The mean of the process is zero. In other words, on average the outcome is zero in the long run.",
    },
  ],
  E32: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      fadeDistant: false,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      processInfo:
        "The mean of the process is zero. In other words, on average the outcome is zero in the long run.",
    },
  ],
  E33: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      fadeDistant: false,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      processInfo:
        "The mean of the process is zero. In other words, on average the outcome is zero in the long run.",
    },
  ],
  E34: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      fadeDistant: false,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      processInfo:
        "The mean of the process is zero. In other words, on average the outcome is zero in the long run.",
    },
  ],
  E35: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      fadeDistant: false,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      processInfo:
        "The mean of the process is zero. In other words, on average the outcome is zero in the long run.",
    },
  ],
  E36: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 600,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      fadeDistant: false,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
      processInfo:
        "The mean of the process is zero. In other words, on average the outcome is zero in the long run.",
    },
  ],
  E41Low: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 4000,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 400 },
  ],
  E42Low: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 4000,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 400 },
  ],
  E43Low: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 4000,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 400 },
  ],
  E44Low: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 4000,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 400 },
  ],
  E45Low: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 4000,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 400 },
  ],
  E46Low: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 4000,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 400 },
  ],
  E41High: [
    {
      rho: 0,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 400,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 4000 },
  ],
  E42High: [
    {
      rho: 0.2,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 400,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 4000 },
  ],
  E43High: [
    {
      rho: 0.4,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 400,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 4000 },
  ],
  E44High: [
    {
      rho: 0.6,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 400,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 4000 },
  ],
  E45High: [
    {
      rho: 0.8,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 400,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 4000 },
  ],
  E46High: [
    {
      rho: 1,
      mu: 0,
      sigma: 20,
      seed: null,
      bonusDivisor: 400,
      trainingRounds: 0,
      testingRounds: 40,
      entryMode: "graphical",
      forecastMode: "1+2",
      showGrayDots: true,
      colorDecay: 0,
      listeningMaterial: false,
      showMean: false,
      clickt: false,
      clickt10: false,
    },
    { bonusDivisor: 4000 },
  ],
};
